from tkinter import *
def myfunc():
    print("This is a demo file ")
root=Tk()
root.geometry("444x888")
filemenu=Menu(root)

m1=Menu(filemenu,tearoff=0)
m1.add_command(label="new project",command=myfunc)
m1.add_separator()
m1.add_command(label="save",command=myfunc)
m1.add_separator()
m1.add_command(label="Save as",command=myfunc)
m1.add_separator()
m1.add_command(label="print",command=myfunc)
m1.add_separator()
m1.add_command(label="Export",command=myfunc)
m1.add_separator()
m1.add_command(label="Exit",command=quit)
m1.add_separator()
root.config(menu=filemenu)
filemenu.add_cascade(label="file",menu=m1)

m2=Menu(filemenu,tearoff=0)
m2.add_command(label="cut",command=myfunc)
m2.add_separator()
m2.add_command(label="copy",command=myfunc)
m2.add_separator()
m2.add_command(label="paste",command=myfunc)
m2.add_separator()
m2.add_command(label="Rename",command=myfunc)
m2.add_separator()
m2.add_command(label="undo",command=myfunc)
m2.add_separator()
m2.add_command(label="Exit",command=quit)
m2.add_separator()
root.config(menu=filemenu)
filemenu.add_cascade(label="Edit",menu=m2)
root.mainloop()